<?php

function setup_scf_array() {
  global $scf;
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd010.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd013.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd015.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd016.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd017.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd018.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd020.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd022.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd024.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd025.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd026.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd027.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd028.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd030.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd031.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd032.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd033.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd034.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd035.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd036.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd037.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd038.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd040.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd041.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd042.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd043.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd044.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd045.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd046.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd047.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd048.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd050.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd051.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd052.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd055.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd060.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd061.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd066.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd070.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd071.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd072.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd074.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd080.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd082.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd083.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd084.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd085.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd086.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd088.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd210.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd222.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd240.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd242.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd243.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd245.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd246.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd247.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd300.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd306.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd307.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd310.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd321.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd340.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd342.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd343.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd351.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd352.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd355.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd357.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd362.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd363.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd365.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd366.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd380.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd381.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd382.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd383.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd384.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd490.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd500.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd501.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd502.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd504.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd505.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd506.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd507.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd508.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd510.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd511.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd513.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd514.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd515.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd516.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd518.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd520.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd521.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd522.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd524.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd525.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd526.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd530.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd533.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd534.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd535.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd536.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd538.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd540.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd541.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd542.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd544.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd545.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd546.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd547.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd550.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd552.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd555.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd556.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd561.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd562.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd563.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd565.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd567.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd580.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd581.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd583.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd584.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd585.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd586.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd588.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd600.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd610.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd611.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd630.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd648.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd650.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd651.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd653.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd654.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd655.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd656.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd657.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd658.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd662.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd69X.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd700.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd710.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd711.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd720.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd730.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd740.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd751.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd752.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd753.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd754.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd760.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd762.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd765.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd767.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd770.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd772.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd773.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd774.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd775.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd776.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd777.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd780.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd785.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd786.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd787.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd800.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd810.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd811.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd830.html';
  $scf[] = 'http://www.loc.gov/marc/holdings/hd841.html';
  $scf[] = 'http://www.loc.gov/marc/holdings/hd842.html';
  $scf[] = 'http://www.loc.gov/marc/holdings/hd843.html';
  $scf[] = 'http://www.loc.gov/marc/holdings/hd844.html';
  $scf[] = 'http://www.loc.gov/marc/holdings/hd845.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd850.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd852.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd856.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd882.html';
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd887.html';
/*
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd853.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd854.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd855.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd863.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd864.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd865.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd866.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd867.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd868.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd876.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd877.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd878.html'; // Hardcoded in tail.xs_
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd880.html'; // Hardcoded in tail.xs_ [no check actually...]
  $scf[] = 'http://www.loc.gov/marc/bibliographic/bd886.html'; // Hardcoded in tail.xs_ [no check actually...]
*/
}
?>
